services:
  - type: web
    name: notaryton-bot
    env: python
    runtime: python-3.11.0
    buildCommand: pip install -r requirements.txt && pytest tests/ -v
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: TON_CENTER_API_KEY
        sync: false
      - key: TON_WALLET_SECRET
        sync: false
      - key: SERVICE_TON_WALLET
        sync: false
      - key: WEBHOOK_URL
        value: https://notaryton.com
      - key: GROUP_IDS
        value: ""
    healthCheckPath: /
